# Generated by Django 6.0.6 on 2026-06-27 18:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador de Plataforma'), ('EMPRESA', 'Empresa (Proveedor)'), ('FREELANCER', 'Vendedor Freelance'), ('TENDERO', 'Tendero (Cliente)')], default='TENDERO', max_length=20, verbose_name='Rol de Usuario')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExamenCertificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Examen')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Examen/Curso')),
                ('empresa', models.ForeignKey(limit_choices_to={'rol': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to=settings.AUTH_USER_MODEL, verbose_name='Empresa Creadora')),
            ],
            options={
                'verbose_name': 'Examen de Certificación',
                'verbose_name_plural': 'Exámenes de Certificación',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado (Por Despachar)'), ('DESPACHADO', 'Despachado'), ('ENTREGADO', 'Entregado al Cliente'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de Pedido')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Comisión del Freelance')),
                ('comision_retenida', models.BooleanField(default=True, verbose_name='Comisión Retenida')),
                ('entrega_confirmada', models.BooleanField(default=False, verbose_name='Entrega Confirmada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'TENDERO'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Tendero (Cliente)')),
                ('empresa', models.ForeignKey(limit_choices_to={'rol': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Empresa Proveedora')),
                ('vendedor_freelance', models.ForeignKey(blank=True, limit_choices_to={'rol': 'FREELANCER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_freelance', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Freelance (Opcional)')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('pasarela_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transacción Pasarela')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('porcentaje_cobrado', models.DecimalField(decimal_places=2, help_text='Porcentaje cobrado (ej: 50.00 o 100.00)', max_digits=5, verbose_name='Porcentaje Cobrado')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='marketplace.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
            },
        ),
        migrations.CreateModel(
            name='PerfilEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('monto_minimo_compra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Mínimo de Compra')),
                ('suscripcion_activa', models.BooleanField(default=False, verbose_name='Suscripción Activa')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Empresa')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa',
                'verbose_name_plural': 'Perfiles de Empresas',
            },
        ),
        migrations.CreateModel(
            name='PerfilFreelance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_calificado', models.BooleanField(default=False, verbose_name='Está Calificado/Certificado')),
                ('usuario', models.OneToOneField(limit_choices_to={'rol': 'FREELANCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='perfil_freelance', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Freelance')),
            ],
            options={
                'verbose_name': 'Perfil de Freelance',
                'verbose_name_plural': 'Perfiles de Freelancers',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Mayorista')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('umbral_bajo_stock', models.IntegerField(default=10, verbose_name='Umbral de Stock Bajo')),
                ('empresa', models.ForeignKey(limit_choices_to={'rol': 'EMPRESA'}, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL, verbose_name='Empresa Proveedora')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='marketplace.pedido', verbose_name='Pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedidos',
            },
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('fecha_presentacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Presentación')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='marketplace.examencertificacion', verbose_name='Examen Rendido')),
                ('freelancer', models.ForeignKey(limit_choices_to={'rol': 'FREELANCER'}, on_delete=django.db.models.deletion.CASCADE, related_name='resultados_examenes', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Freelance')),
            ],
            options={
                'verbose_name': 'Resultado de Examen',
                'verbose_name_plural': 'Resultados de Exámenes',
                'unique_together': {('freelancer', 'examen')},
            },
        ),
    ]
