# Generated by Django 6.0.6 on 2026-06-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilempresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa/logos/', verbose_name='Logo de la Empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vista_previa',
            field=models.ImageField(blank=True, null=True, upload_to='producto/previews/', verbose_name='Vista Previa / Imagen'),
        ),
    ]
