# Generated by Django 6.0.6 on 2026-07-27 21:51

import marketplace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_tokensesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokensesion',
            name='expira',
            field=models.DateTimeField(default=marketplace.models._expiracion_default, verbose_name='Fecha de Expiracion'),
        ),
    ]
